{% set name = "snowpipe-streaming" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  build:
    # curl is needed only for downloading whl files in build.sh and bld.bat
    - curl
  host:
    - pip
    - python 3.9
    - wheel
    - msgspec ==0.19.0
  run:
    - python >=3.9
    - msgspec ==0.19.0

test:
  imports:
    - snowflake.ingest.streaming
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snowflakedb/snowflake-ingest-sdk
  summary: Snowflake Streaming Ingest SDK
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE-2.0.txt
  description: |
    A high-performance Python SDK for streaming data ingestion into Snowflake, built with Rust for optimal performance and reliability.
  dev_url: https://github.com/snowflakedb/snowflake-ingest-sdk
  doc_url: https://docs.snowflake.com

extra:
  recipe-maintainers:
    - aosipov